### ISSUE TITLE
Login fails since 30.Jan 2024

### ISSUE THREAD

**Issue by LudwigWen** [SiKreuz/SZ2pdf#1]
I think SZ changed loginside to toke generation. 

Ich selbst habe leider Null Erfahrung mit Browserautomatisierung und kann keinen Fix erstellen.

ich hoffe du findest die nötige Zeit für einen Bugfix. 

Ich und Sohn haben selbst an der TUM studiert und wir wissen, da bleibt wenig Zeit für sowie. 

Danke trotzdem schon vorab.

**Comment by xorbital** [comment]
Ich habe keinen Zugriff auf das epaper, daher müsstest du mal testen ob das hier klappt:
Klone die Repo, öffne die Datei `src/SZ2pdf.py` und ersetze Zeile 12 durch:
```
LOGIN_URL = 'https://auth.sueddeutsche.de/id/api/v1/identity/vxauth/authorize?client_id=oUziPp2Dpe&redirect_uri=https%3A%2F%2Fepaper.sueddeutsche.de'
```
Falls das nicht reicht, ersetze zusätzlich in der selben Datei, Zeile 38 durch:
```
br.form['current-password'] = password
```
Wie gesagt, ich kann nicht überprüfen ob das funktioniert, aber es scheint als hätte die SZ einen externen Auth-Dienst eingeführt.

**Comment by SiKreuz** [comment]
@LudwigWen Danke fürs darauf aufmerksam machen. Ich schau bei Zeiten mal rein und versuche einen Fix zu erstellen. Kann dir aber nicht sagen, wann das sein wird.

**Comment by SiKreuz** [comment]
@LudwigWen I had a look at it some time ago and the changes basically require a full rewrite as the whole login process is different now. Also not super straight forward as it was before. It is not really priority for me now, when I have time I will look into it again. If you want to look at it yourself, feel free to help out! :)
